# docker-compose.yml
version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: codifai-postgres
    environment:
      POSTGRES_DB: codifai
      POSTGRES_USER: radia
      POSTGRES_PASSWORD: radia
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
